### PR TITLE
Don't fail on not supported geometry.

### LINKED ISSUE #26: Support printing circles
Currently, we don't support this geometry.

It's a bit a special one. I'll encode it as a point.

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix #26 

Circles are not possible in GeoJson. I encode them as Polygon.
I also split a big method in two and the big deepEqual in tests, because that was hard to debug.

### CODE REVIEW

File: src/constants.ts [hunk 1]
```diff
@@ -5,6 +5,8 @@ export const Constants = {
   DOTS_PER_INCH: 72,
   /** According to the "international yard" definition 1 inch is defined as exactly 2.54 cm. */
   METERS_PER_INCH: 0.0254,
+  /** Vector circles are rendered as polygon of N sides. */
+  CIRCLE_TO_POLYGON_SIDES: 64,
```
Comment (ismailsunni) [inline src/constants.ts:9]: Any reason to use 64? In OL  the default is 32. Just curious. https://openlayers.org/en/latest/apidoc/module-ol_geom_Polygon.html#.fromCircle

**Review by ismailsunni — APPROVED** [review]
LGTM

**Review by gberaudo — APPROVED** [review]
